#sudo apt update && sudo apt install ansible -y

---
# Arquivo YAML do ansible para instalar alguns pacotes relevantes

- hosts: all
  # Tornar-se usuário root antes de executar as tarefas
  become: yes
  tasks:
    # Utilizando o módulo package do ansible e o loop with_items para instalar os pacotes
    - name: Instalar pacotes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        # Lista de pacotes a serem instalados
        - httpd
        - unzip
        - git
        - htop
        - curl
        - wget
        - tree
        - bash-completion